/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by mist-orm from models/post.ts
 * Generated at: 2025-11-16
 */
import { pgTable, uuid, text, boolean, timestamp } from 'drizzle-orm/pg-core'
import { users } from './users'

export const posts = pgTable('posts', {
  id: uuid('id').defaultRandom().primaryKey(),
  title: text('title').notNull(),
  content: text('content').notNull(),
  userId: uuid('user_id').notNull().references(() => users.id),
  published: boolean('published').notNull(),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
})
