/**
 * Migration generation using drizzle-kit
 */

import { spawn } from 'node:child_process'
import * as fs from 'node:fs/promises'
import * as path from 'node:path'
import type { ResolvedMistConfig } from '../config/types'

/**
 * Generate drizzle.config.ts for drizzle-kit
 */
export async function generateDrizzleConfig(
  outputDir: string,
  databaseType: 'postgres' | 'sqlite',
  connectionString: string
): Promise<string> {
  const configPath = path.join(outputDir, 'drizzle.config.ts')
  const schemaPath = './schema'
  const migrationsPath = './migrations'

  // Determine dialect
  const dialect = databaseType === 'postgres' ? 'postgresql' : 'sqlite'

  // Generate config content
  const configContent = `/**
 * Drizzle Kit configuration
 * Auto-generated by mist-orm
 */

import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: '${dialect}',
  schema: '${schemaPath}',
  out: '${migrationsPath}',
  dbCredentials: ${
    databaseType === 'postgres'
      ? `{
    url: process.env.DATABASE_URL || '${connectionString}',
  }`
      : `{
    url: '${connectionString}',
  }`
  },
})
`

  await fs.writeFile(configPath, configContent, 'utf-8')

  return configPath
}

/**
 * Run drizzle-kit generate to create migrations
 */
export async function generateMigrations(
  outputDir: string,
  configPath: string
): Promise<{ success: boolean; output: string; error?: string }> {
  return new Promise((resolve, reject) => {
    const drizzleKitPath = require.resolve('drizzle-kit')
    const drizzleKitBin = path.join(path.dirname(drizzleKitPath), '../bin.cjs')

    // Spawn drizzle-kit generate process
    const proc = spawn('node', [drizzleKitBin, 'generate', '--config', configPath], {
      cwd: outputDir,
      env: { ...process.env, FORCE_COLOR: '0' },
    })

    let output = ''
    let errorOutput = ''

    proc.stdout?.on('data', data => {
      output += data.toString()
    })

    proc.stderr?.on('data', data => {
      errorOutput += data.toString()
    })

    proc.on('error', error => {
      reject(new Error(`Failed to spawn drizzle-kit: ${error.message}`))
    })

    proc.on('close', code => {
      if (code === 0) {
        resolve({
          success: true,
          output: output + errorOutput,
        })
      } else {
        resolve({
          success: false,
          output: output + errorOutput,
          error: `drizzle-kit exited with code ${code}`,
        })
      }
    })
  })
}

/**
 * Get the list of migration files
 */
export async function listMigrationFiles(outputDir: string): Promise<string[]> {
  const migrationsDir = path.join(outputDir, 'migrations')

  try {
    const files = await fs.readdir(migrationsDir)

    // Filter for .sql files and sort
    const sqlFiles = files
      .filter(f => f.endsWith('.sql'))
      .sort((a, b) => a.localeCompare(b))

    return sqlFiles
  } catch (error) {
    // Directory doesn't exist yet
    return []
  }
}

/**
 * Read a migration file's content
 */
export async function readMigrationFile(
  outputDir: string,
  filename: string
): Promise<string> {
  const migrationsDir = path.join(outputDir, 'migrations')
  const filePath = path.join(migrationsDir, filename)

  return await fs.readFile(filePath, 'utf-8')
}

/**
 * Generate a migration from schema changes
 */
export async function generateMigration(
  config: ResolvedMistConfig
): Promise<{
  success: boolean
  migrationFiles: string[]
  output: string
  error?: string
}> {
  try {
    // Ensure migrations directory exists
    const migrationsDir = path.join(config.output, 'migrations')
    await fs.mkdir(migrationsDir, { recursive: true })

    // Generate drizzle.config.ts
    const configPath = await generateDrizzleConfig(
      config.output,
      config.database.type,
      config.connection
    )

    // Run drizzle-kit generate
    const result = await generateMigrations(config.output, configPath)

    if (!result.success) {
      return {
        success: false,
        migrationFiles: [],
        output: result.output,
        error: result.error,
      }
    }

    // Get the list of generated migration files
    const migrationFiles = await listMigrationFiles(config.output)

    return {
      success: true,
      migrationFiles,
      output: result.output,
    }
  } catch (error) {
    return {
      success: false,
      migrationFiles: [],
      output: '',
      error: error instanceof Error ? error.message : String(error),
    }
  }
}
