/**
 * Client code generator - generates typed database client
 */

import type { GeneratedSchema } from './postgres'

export interface ClientGenerationOptions {
  schemas: GeneratedSchema[]
  databaseType: 'postgres' | 'sqlite'
  connectionString?: string
}

/**
 * Generates the typed client code
 */
export function generateClient(options: ClientGenerationOptions): string {
  const { schemas, databaseType } = options

  const header = `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by mist-orm
 *
 * Type-safe database client with CRUD operations for each table
 */`

  const imports = generateImports(databaseType, schemas)
  const connectionCode = generateConnectionCode(databaseType)
  const tableClients = schemas.map(schema => generateTableClient(schema, databaseType)).join('\n\n')
  const clientExport = generateClientExport(schemas)

  return `${header}\n\n${imports}\n\n${connectionCode}\n\n${tableClients}\n\n${clientExport}\n`
}

/**
 * Generates import statements
 */
function generateImports(databaseType: 'postgres' | 'sqlite', schemas: GeneratedSchema[]): string {
  const imports = [
    `import { createConnection } from '../runtime/connection.js'`,
    `import { insert, findOne, findMany, update, deleteRecords } from '../runtime/operations.js'`,
    `import * as schema from './schema/index.js'`,
  ]

  // Add type imports for each table
  for (const s of schemas) {
    const pascalName = toPascalCase(s.tableName)
    imports.push(`import type { ${pascalName}, New${pascalName} } from './types/${s.tableName}.js'`)
  }

  return imports.join('\n')
}

/**
 * Generates connection initialization code
 */
function generateConnectionCode(databaseType: 'postgres' | 'sqlite'): string {
  return `// Database connection
// The connection string should be provided via environment variable or config
const connectionString = process.env.DATABASE_URL || process.env.MIST_DATABASE_URL || ''

if (!connectionString) {
  throw new Error('Database connection string not provided. Set DATABASE_URL or MIST_DATABASE_URL environment variable.')
}

const dbPromise = createConnection({ connectionString, type: '${databaseType}' })`
}

/**
 * Generates client code for a single table
 */
function generateTableClient(schema: GeneratedSchema, databaseType: 'postgres' | 'sqlite'): string {
  const pascalName = toPascalCase(schema.tableName)

  return `/**
 * Client for ${schema.tableName} table
 */
export const ${schema.tableName} = {
  /**
   * Insert a new ${schema.tableName} record
   */
  async insert(data: New${pascalName}): Promise<${pascalName}> {
    const db = await dbPromise
    return insert<${pascalName}>(db, schema.${schema.tableName}, data as Record<string, unknown>)
  },

  /**
   * Find a single ${schema.tableName} record
   */
  async findOne(where: Partial<${pascalName}>): Promise<${pascalName} | null> {
    const db = await dbPromise
    return findOne<${pascalName}>(db, schema.${schema.tableName}, where)
  },

  /**
   * Find multiple ${schema.tableName} records
   */
  async findMany(where?: Partial<${pascalName}>): Promise<${pascalName}[]> {
    const db = await dbPromise
    return findMany<${pascalName}>(db, schema.${schema.tableName}, where)
  },

  /**
   * Update ${schema.tableName} records
   */
  async update(where: Partial<${pascalName}>, data: Partial<${pascalName}>): Promise<number> {
    const db = await dbPromise
    return update<${pascalName}>(db, schema.${schema.tableName}, where, data)
  },

  /**
   * Delete ${schema.tableName} records
   */
  async delete(where: Partial<${pascalName}>): Promise<number> {
    const db = await dbPromise
    return deleteRecords<${pascalName}>(db, schema.${schema.tableName}, where)
  },
}`
}

/**
 * Generates the main db client export
 */
function generateClientExport(schemas: GeneratedSchema[]): string {
  const tableExports = schemas.map(s => `  ${s.tableName},`).join('\n')

  return `/**
 * Main database client
 * Usage:
 *   import { db } from '.mist/client'
 *   const user = await db.users.findOne({ id: '123' })
 */
export const db = {
${tableExports}
}`
}

/**
 * Converts table name to PascalCase for type names
 */
function toPascalCase(str: string): string {
  return str
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('')
}
