/**
 * TypeScript type file generator
 * Generates type definitions inferred from Drizzle schemas
 */

import type { GeneratedSchema } from './postgres'

/**
 * Generates TypeScript type file for a schema
 */
export function generateTypeFile(schema: GeneratedSchema): string {
  const pascalName = toPascalCase(schema.tableName)

  const header = `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by mist-orm
 *
 * TypeScript types for ${schema.tableName} table
 */`

  const imports = `import type { InferSelectModel, InferInsertModel } from 'drizzle-orm'
import { ${schema.tableName} } from '../schema/${schema.tableName}.js'`

  const types = `/**
 * ${pascalName} record (for queries)
 */
export type ${pascalName} = InferSelectModel<typeof ${schema.tableName}>

/**
 * New ${pascalName} data (for inserts)
 */
export type New${pascalName} = InferInsertModel<typeof ${schema.tableName}>`

  return `${header}\n\n${imports}\n\n${types}\n`
}

/**
 * Generates the types index file
 */
export function generateTypesIndex(schemas: GeneratedSchema[]): string {
  const header = `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by mist-orm
 *
 * Exports all generated types
 */`

  const exports = schemas
    .map(schema => {
      const pascalName = toPascalCase(schema.tableName)
      return `export type { ${pascalName}, New${pascalName} } from './${schema.tableName}.js'`
    })
    .join('\n')

  return `${header}\n\n${exports}\n`
}

/**
 * Converts table name to PascalCase
 */
function toPascalCase(str: string): string {
  return str
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join('')
}
