/**
 * File writer for generated schemas
 */

import { mkdir, writeFile, access } from 'fs/promises'
import { join } from 'path'
import type { GeneratedSchema } from './postgres'
import { generateTypeFile, generateTypesIndex } from './types-gen'
import { generateClient } from './client'

/**
 * File system abstraction for testability
 */
export interface FileSystem {
  mkdir(path: string, options?: { recursive?: boolean }): Promise<void>
  writeFile(path: string, data: string, encoding: BufferEncoding): Promise<void>
  exists(path: string): Promise<boolean>
}

/**
 * Default file system implementation
 */
export const defaultFileSystem: FileSystem = {
  async mkdir(path, options) {
    await mkdir(path, options)
  },
  async writeFile(path, data, encoding) {
    await writeFile(path, data, encoding)
  },
  async exists(path) {
    try {
      await access(path)
      return true
    } catch {
      return false
    }
  },
}

/**
 * Topologically sorts schemas based on dependencies
 * Returns sorted schemas and any warnings about circular dependencies or missing tables
 */
function topologicalSort(schemas: GeneratedSchema[]): {
  sorted: GeneratedSchema[]
  warnings: string[]
} {
  const sorted: GeneratedSchema[] = []
  const visited = new Set<string>()
  const visiting = new Set<string>()
  const warnings: string[] = []
  const tableNames = new Set(schemas.map(s => s.tableName))

  function visit(schema: GeneratedSchema) {
    if (visited.has(schema.tableName)) {
      return
    }

    if (visiting.has(schema.tableName)) {
      // Circular dependency detected
      warnings.push(
        `Circular dependency detected involving table '${schema.tableName}'. ` +
        `This may cause issues with foreign key constraints.`
      )
      return
    }

    visiting.add(schema.tableName)

    // Visit dependencies first
    for (const dep of schema.referencedTables) {
      // Check if referenced table exists
      if (!tableNames.has(dep)) {
        warnings.push(
          `Table '${schema.tableName}' references '${dep}' which was not found in the generated schemas. ` +
          `Make sure the '${dep}' interface is exported.`
        )
        continue
      }

      const depSchema = schemas.find(s => s.tableName === dep)
      if (depSchema) {
        visit(depSchema)
      }
    }

    visiting.delete(schema.tableName)
    visited.add(schema.tableName)
    sorted.push(schema)
  }

  for (const schema of schemas) {
    visit(schema)
  }

  return { sorted, warnings }
}

/**
 * Generates the schema index file content
 */
function generateIndexFile(schemas: GeneratedSchema[]): {
  content: string
  warnings: string[]
} {
  const { sorted, warnings } = topologicalSort(schemas)

  const header = `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by mist-orm
 *
 * This file exports all generated schemas in dependency order
 */`

  const exports = sorted.map(schema => `export * from './${schema.tableName}'`).join('\n')

  return {
    content: `${header}\n\n${exports}\n`,
    warnings,
  }
}

/**
 * Writes generated schemas to disk
 * Returns any warnings about circular dependencies or missing tables
 */
export async function writeSchemas(
  schemas: GeneratedSchema[],
  outputDir: string,
  databaseType: 'postgres' | 'sqlite',
  fs: FileSystem = defaultFileSystem
): Promise<string[]> {
  const schemaDir = join(outputDir, 'schema')
  const typesDir = join(outputDir, 'types')

  // Create directories
  await fs.mkdir(schemaDir, { recursive: true })
  await fs.mkdir(typesDir, { recursive: true })

  // Write individual schema files
  for (const schema of schemas) {
    const filePath = join(schemaDir, `${schema.tableName}.ts`)
    await fs.writeFile(filePath, schema.code, 'utf-8')
  }

  // Write schema index file
  const indexPath = join(schemaDir, 'index.ts')
  const { content: indexContent, warnings } = generateIndexFile(schemas)
  await fs.writeFile(indexPath, indexContent, 'utf-8')

  // Write individual type files
  for (const schema of schemas) {
    const typeFilePath = join(typesDir, `${schema.tableName}.ts`)
    const typeContent = generateTypeFile(schema)
    await fs.writeFile(typeFilePath, typeContent, 'utf-8')
  }

  // Write types index file
  const typesIndexPath = join(typesDir, 'index.ts')
  const typesIndexContent = generateTypesIndex(schemas)
  await fs.writeFile(typesIndexPath, typesIndexContent, 'utf-8')

  // Write client file
  const clientPath = join(outputDir, 'client.ts')
  const clientContent = generateClient({ schemas, databaseType })
  await fs.writeFile(clientPath, clientContent, 'utf-8')

  return warnings
}
