/**
 * File writer for generated schemas
 */

import { mkdir, writeFile, access } from 'fs/promises'
import { join } from 'path'
import type { GeneratedSchema } from './postgres'

/**
 * File system abstraction for testability
 */
export interface FileSystem {
  mkdir(path: string, options?: { recursive?: boolean }): Promise<void>
  writeFile(path: string, data: string, encoding: BufferEncoding): Promise<void>
  exists(path: string): Promise<boolean>
}

/**
 * Default file system implementation
 */
export const defaultFileSystem: FileSystem = {
  async mkdir(path, options) {
    await mkdir(path, options)
  },
  async writeFile(path, data, encoding) {
    await writeFile(path, data, encoding)
  },
  async exists(path) {
    try {
      await access(path)
      return true
    } catch {
      return false
    }
  },
}

/**
 * Topologically sorts schemas based on dependencies
 */
function topologicalSort(schemas: GeneratedSchema[]): GeneratedSchema[] {
  const sorted: GeneratedSchema[] = []
  const visited = new Set<string>()
  const visiting = new Set<string>()

  function visit(schema: GeneratedSchema) {
    if (visited.has(schema.tableName)) {
      return
    }

    if (visiting.has(schema.tableName)) {
      // Circular dependency - just continue
      return
    }

    visiting.add(schema.tableName)

    // Visit dependencies first
    for (const dep of schema.referencedTables) {
      const depSchema = schemas.find(s => s.tableName === dep)
      if (depSchema) {
        visit(depSchema)
      }
    }

    visiting.delete(schema.tableName)
    visited.add(schema.tableName)
    sorted.push(schema)
  }

  for (const schema of schemas) {
    visit(schema)
  }

  return sorted
}

/**
 * Generates the schema index file content
 */
function generateIndexFile(schemas: GeneratedSchema[]): string {
  const sorted = topologicalSort(schemas)

  const header = `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Generated by mist-orm
 *
 * This file exports all generated schemas in dependency order
 */`

  const exports = sorted.map(schema => `export * from './${schema.tableName}'`).join('\n')

  return `${header}\n\n${exports}\n`
}

/**
 * Writes generated schemas to disk
 */
export async function writeSchemas(
  schemas: GeneratedSchema[],
  outputDir: string,
  fs: FileSystem = defaultFileSystem
): Promise<void> {
  const schemaDir = join(outputDir, 'schema')

  // Create directories
  await fs.mkdir(schemaDir, { recursive: true })

  // Write individual schema files
  for (const schema of schemas) {
    const filePath = join(schemaDir, `${schema.tableName}.ts`)
    await fs.writeFile(filePath, schema.code, 'utf-8')
  }

  // Write index file
  const indexPath = join(schemaDir, 'index.ts')
  const indexContent = generateIndexFile(schemas)
  await fs.writeFile(indexPath, indexContent, 'utf-8')
}
